# app.yaml
---
service: hello
runtime: java11
env_variables:
  SPRING_PROFILES_ACTIVE: gcp
instance_class: B2
basic_scaling:
  max_instances: 1
  idle_timeout: 5m
health_check:
  enable_health_check: False
